### ISSUE TITLE
Anchor while not on a boat

### ISSUE THREAD

**Issue by TobiasThaisen** [TanguyOrtegat/jb_anchorboat#1]
You can still use the anchor if you are not on any boat, like use it anywhere

**Comment by TanguyOrtegat** [comment]
you mean we need to check if he is still near a boat ?

**Comment by TobiasThaisen** [comment]
Yeah i just made a simple else and a wait so he have to anchor the boat in 5 seconds

**Comment by TanguyOrtegat** [comment]
yea but then you cannot de-anchor the boat

**Comment by TobiasThaisen** [comment]
If the engine is turned on then the anchor would go up

**Comment by Thaisen69** [comment]
If the engine is turned on then the anchor would go up

**Comment by TanguyOrtegat** [comment]
i did add small code , should fix your thing. the only thing is if you want to reanchor your boat you must seat your boat then go off the boat so that you can anchor and deanchor once
